print('''         ************************************
            KARMA PARAMETRELERI KULLANARAK
                  BJT AC ANALIZI 
         ************************************''')
print("Bu program bir BJT devresinin AC analizini ")
print("Karma parametreleri kullanarak gerceklestirir")
print()
print("Asagidaki devre degerlerini giriniz:")
R1 = float(input("R1 = "))
R2 = float(input("R2 = "))
RC = float(input("RC = "))
print()
RL = float(input("Yuk Direnci = "))
RS = float(input("Kaynak Direnci = "))
VS = float(input("Kaynak Gerilimi = "))
print()
print("BJT ' nin karma parametresi degerlerini giriniz : ")
HI = float(input("HI = "))
HF = float(input("HF = "))
HO = float(input("HO = "))
HR = float(input("HR = "))
print()
# Karma parametreleri kullanarak ac hesaplamarini yapan modul
RP = RC * RL / (RC + RL)
RZ = HI - HF * HR * RP / (1 * HO * RP)
RB = R1 * R2 /(R1 * R2)
RI = RZ * RB / (RZ + RB)
if HO != 0 and HR != 0:
    RT = 1/(HO - HF * HR / (HI + RS))
else:
    RT = float(input("Not = 1E + 30 degerini giriniz/n RT = "))
RO = RT * RC / (RT + RC)
AI = (RB / (RB + RZ)) * (HF / (1 + HO * RP)) * (RC / RL)
if AI <0.000001 :
    AI = 0
AV = HI + RC / (HI + (HI * HO - HF * HR) * RC)
VI = RI * VS / (RI + RS)
VO = AV * VI
VL = AV * RL / (RP + RL)
print()
print(" AC analiz sonuclari ")
print()
print("Giris empedansi , RI = " + str(RI / 1000) + " kiloohm")
print("cikis empedansi , RO = " + str(RO / 1000) + " kiloohm")
print("Gerilim kazanci ( yuksuz ) , AV = " + str(AV))
print("Akim Kazanci (IL / Ii) , AI = " + str(AI))
print()
print("cikis gerilimi (yuksuz) , VO = " + str(VO) + " volt")
print()
print("cikis gerilimi (yuk mevcut) , VL = " + str(VL) + " volt")
print()
print()
print()
print('''         *****************************************
            re ve BETA PARAMETRELERI KULLANARAK
                  BJT AC ANALIZI 
         *****************************************''')
print("Bu program re ve beta parametreleri kullanarak ")
print("bir BJT ' nin ac analizi gerceklerstirir")
print()
print("Asagidaki devre degerlerini giriniz:")
R1 = float(input("R1 = "))
R2 = float(input("R2 = "))
RC = float(input("RC = "))
print()
E1 = float(input("KOPRULENMIS EMETOR DIRENCI = "))
E2 = float(input("KOPRULENEN EMETOR DIRENCI = "))
print()
beta = float(input("BETA = "))
CC = float(input("Beslenme gerilimi = "))
RL = float(input("Yuk direnci = "))
RS = float(input("Kaynak direnci = "))
VS = float(input("Kaynak gerilimi = "))
print()
# re modelini kullanarak BJT hesaplamarini yapan modul
RB = R1 * (R2 / (R1 + R2))
RP = RC * (RL / (RC + RL))
BB = R2 * CC / (R1 + R2)
IE = (BB - 0.7) * (beta + 1)/(RB + beta * (E1 + E2))
RE = 0.026 / IE
R3 = beta * (RE + E1)
RI = RB * (R3 / (RB + R3))
AV = -RC / (E1 + RE)
VI = VS * (R1 / (RI + RS))
VO = AV * VI
VL = VO * (RL / (RO + RL)) 
VM = CC - IE *(beta / beta + 1) * (RC + E1 + E2)
print()
print(" AC analiz sonuclari ")
print()
print("Transistorun dinamik direncii , RE = " + str(RE) + " ohm")
print() 
if CC - IE * (RC + E1 +E2 ) <= 0:
    print("Devre doymada")
    VM = CC - IE *(beta / beta + 1) * (RC + E1 + E2) # Max distorsiyonsuz sapmasi
if abs(VL) > VM :
    print("Maximim distorsiyonsuz cikis :" + str(VM) + " volt")
print("Giris empedansi , RI = " + str(RI) + " ohm")
print("cikis empedansi , RO = " + str(RO) + " ohm")
print("Gerilim kazanci (yuksuz) , AV = " + str(AV))
print("Akim kazanci , AI = " + str(AI))
print()
print("cikis gerilimi (yuksuz) , VO = " + str(VO) + " volt")
print("cikis gerilimi (yuk - altinda) , VL = " + str(VL) + " volt")